import type { Metadata } from "next";
import { EB_Garamond, Figtree } from "next/font/google";
import "./globals.css";
import "./styles/typography.css";
import "./styles/spacings.css";
import "./styles/components.css";
import "./styles/buttons.css";
import Navbar from "./components/Navbar/Navbar";

const figtree = Figtree({
    subsets: ["latin"],
    weight: ["400", "500", "600"],
    variable: "--font-figtree",
    display: "swap",
});

const garamond = EB_Garamond({
    subsets: ["latin"],
    weight: ["400", "500", "600", "700"],
    variable: "--font-garamond",
    display: "swap",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${garamond.variable} ${figtree.variable} antialiased`}
            >
                <Navbar />
                {children}
            </body>
        </html>
    );
}
