import type { Metadata } from "next";
import { EB_Garamond, Figtree } from "next/font/google";
import "./globals.css";
import "./styles/typography.css";
import "./styles/spacings.scss";
import "./styles/components/components.scss";
import "./styles/buttons.scss";
import "./styles/swiper.scss";
import Navbar from "./components/Navbar/Navbar";
import MobileClassHandler from "./components/MobileClassHandler";

const figtree = Figtree({
    subsets: ["latin"],
    weight: ["400", "500", "600"],
    variable: "--font-figtree",
    display: "swap",
});

const garamond = EB_Garamond({
    subsets: ["latin"],
    weight: ["400", "500", "600", "700"],
    variable: "--font-garamond",
    display: "swap",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

let viewportWidth: number | undefined = undefined;
if (typeof window !== "undefined") {
    viewportWidth = window.innerWidth;
    console.log("Viewport width:", viewportWidth);
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${garamond.variable} ${figtree.variable} antialiased ${
                    viewportWidth && viewportWidth <= 768 ? "mobile" : ""
                }`}
            >
                <MobileClassHandler />
                <Navbar />
                {children}
            </body>
        </html>
    );
}
